### ISSUE TITLE
Neļauj izspēlēt kārti

### ISSUE THREAD

**Issue by Pukinens** [Camel-RD/ZoleX#1]
Pēdējais gājiens. Lielais Askolds iziet pīķis 9, Haralds pīķis 10. Man neļauj izspēlēt pīķa dāmu ar paziņojumu "šī kārts nederēs" (vai kautkā līdzīgi).

**Comment by Camel-RD** [comment]
Dažreiz neparādās kārts bilde, tās vietā ir tukšums.
Mēģināju kautko pamainīt, cerams, ka tagad būs izlabots, jāpatestē ilgāk

**Comment by Camel-RD** [comment]
Izskatās, ka viss darbojas normāli
